import { DispatchJob, AgentResult, ResultStatus } from "../types";

/**
 * T051 (Part 1): Hermes Orchestration Insight Generator
 *
 * Summarizes dispatch cycle:
 * - Tasks dispatched
 * - Tasks approved
 * - Tasks skipped (timeout)
 * - Tasks blocked
 *
 * Pure function, zero side effects, returns Markdown string.
 */

export interface OrchestrationCycleSummary {
  timestamp: string;
  totalDispatched: number;
  byStatus: Record<string, number>;
  byRiskLevel: Record<string, number>;
  completedTasks: number;
  failedTasks: number;
  timedOutTasks: number;
  blockedTasks: number;
}

export function generateOrchestrationInsight(
  jobs: DispatchJob[],
  results: AgentResult[]
): string {
  const summary = summarizeOrchestration(jobs, results);

  return `# Orchestration Cycle Summary

**Timestamp**: ${new Date(summary.timestamp).toLocaleString()}

## Dispatch Overview

- **Total Dispatched**: ${summary.totalDispatched}
- **Completed**: ${summary.completedTasks}
- **Failed**: ${summary.failedTasks}
- **Timed Out**: ${summary.timedOutTasks}
- **Blocked**: ${summary.blockedTasks}

## Status Breakdown

${Object.entries(summary.byStatus)
  .map(([status, count]) => `- **${capitalize(status)}**: ${count}`)
  .join("\n")}

## Risk Level Distribution

${Object.entries(summary.byRiskLevel)
  .map(([level, count]) => `- **${capitalize(level)}**: ${count}`)
  .join("\n")}

## Key Observations

${generateKeyObservations(summary)}

## Recommendations

${generateOrchestrationRecommendations(summary)}

---
*Generated by Hermes (Observation Only — No Code Execution)*
`;
}

function summarizeOrchestration(
  jobs: DispatchJob[],
  results: AgentResult[]
): OrchestrationCycleSummary {
  const byStatus: Record<string, number> = {
    queued: 0,
    running: 0,
    approved: 0,
    skipped_due_to_risk: 0,
    completed: 0,
    failed: 0,
  };

  const byRiskLevel: Record<string, number> = {
    safe: 0,
    low: 0,
    medium: 0,
    high: 0,
    critical: 0,
  };

  jobs.forEach((job) => {
    byStatus[job.status]++;
    byRiskLevel[job.riskLevel]++;
  });

  const completedTasks = byStatus.completed;
  const failedTasks = byStatus.failed;
  const timedOutTasks = byStatus.skipped_due_to_risk;
  const blockedTasks = results.filter(
    (r) => r.resultStatus === "blocked"
  ).length;

  return {
    timestamp: new Date().toISOString(),
    totalDispatched: jobs.length,
    byStatus,
    byRiskLevel,
    completedTasks,
    failedTasks,
    timedOutTasks,
    blockedTasks,
  };
}

function generateKeyObservations(summary: OrchestrationCycleSummary): string {
  const obs: string[] = [];

  if (summary.completedTasks > 0) {
    obs.push(
      `✅ **${summary.completedTasks} tasks** successfully completed.`
    );
  }

  if (summary.timedOutTasks > 0) {
    obs.push(
      `⏱️ **${summary.timedOutTasks} tasks** skipped due to approval timeout.`
    );
  }

  if (summary.failedTasks > 0) {
    obs.push(
      `❌ **${summary.failedTasks} tasks** failed and require investigation.`
    );
  }

  if (summary.blockedTasks > 0) {
    obs.push(`🚫 **${summary.blockedTasks} tasks** are blocked.`);
  }

  const criticalCount = summary.byRiskLevel.critical || 0;
  if (criticalCount > 0) {
    obs.push(
      `⚠️ **${criticalCount} critical-risk tasks** in queue — ensure approval.`
    );
  }

  if (obs.length === 0) {
    obs.push("No significant observations in this cycle.");
  }

  return obs.map((o) => `- ${o}`).join("\n");
}

function generateOrchestrationRecommendations(
  summary: OrchestrationCycleSummary
): string {
  const rec: string[] = [];

  if (summary.timedOutTasks > summary.completedTasks * 0.5) {
    rec.push(
      "🔔 High timeout rate — consider extending approval window or reducing task risk."
    );
  }

  if (summary.failedTasks > 0) {
    rec.push(
      "📝 Review failed tasks for patterns — may indicate prompt quality issue."
    );
  }

  if ((summary.byRiskLevel.critical || 0) > 5) {
    rec.push("⛔ Many critical-risk tasks in queue — pace approvals carefully.");
  }

  if (summary.completedTasks === summary.totalDispatched) {
    rec.push("✨ All tasks completed successfully — excellent cycle!");
  }

  if (rec.length === 0) {
    rec.push("Continue monitoring orchestration health.");
  }

  return rec.map((r) => `- ${r}`).join("\n");
}

function capitalize(s: string): string {
  return s
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
