import { AgentResult, AgentType, ResultStatus } from "../types";

/**
 * T051 (Part 3): Routing Recommendation
 *
 * Suggests next agent based on current performance distribution.
 * Pure function, returns Markdown string.
 */

export interface RoutingScore {
  agent: AgentType;
  recommendationScore: number; // 0-100
  reasoning: string;
}

export function generateRoutingRecommendation(
  results: AgentResult[],
  taskContext?: {
    title?: string;
    type?: string;
    riskLevel?: string;
  }
): string {
  const recommendations = calculateRoutingScores(results, taskContext);

  if (recommendations.length === 0) {
    return `# Routing Recommendation

No performance history yet. Default recommendations:
- **New to project**: Claude Code (architecture, research)
- **Clear implementation**: Codex (bounded coding, tests)
- **UI/Visual work**: Antigravity (components, design)

---
*Generated by Hermes (Observation Only)*
`;
  }

  const topRecommendation = recommendations[0];

  return `# Routing Recommendation

## Primary Recommendation

**Agent**: ${topRecommendation.agent}
**Confidence**: ${topRecommendation.recommendationScore}%
**Reasoning**: ${topRecommendation.reasoning}

## Alternative Agents

${recommendations
  .slice(1)
  .map(
    (rec) => `- **${rec.agent}** (${rec.recommendationScore}%): ${rec.reasoning}`
  )
  .join("\n")}

## Routing Strategy

Based on historical performance:

${generateRoutingStrategy(recommendations)}

---
*Generated by Hermes (Observation Only — No Code Execution)*
`;
}

function calculateRoutingScores(
  results: AgentResult[],
  taskContext?: { title?: string; type?: string; riskLevel?: string }
): RoutingScore[] {
  const agents: AgentType[] = ["claude-code", "codex", "antigravity"];
  const scores: RoutingScore[] = [];

  agents.forEach((agent) => {
    const agentResults = results.filter((r) => r.agentId === agent);

    if (agentResults.length === 0) {
      // No history: assign neutral score with reason
      scores.push({
        agent,
        recommendationScore: 50,
        reasoning: "No performance history yet.",
      });
      return;
    }

    // Calculate performance metrics
    const passCount = agentResults.filter(
      (r) => r.resultStatus === "pass"
    ).length;
    const minorFixCount = agentResults.filter(
      (r) => r.resultStatus === "minor_fix"
    ).length;
    const blockedCount = agentResults.filter(
      (r) => r.resultStatus === "blocked"
    ).length;
    const safetyCount = agentResults.filter(
      (r) => r.resultStatus === "safety_violation"
    ).length;

    const successRate = (passCount / agentResults.length) * 100;
    const needsFixRate = ((passCount + minorFixCount) / agentResults.length) * 100;

    // Base score on success
    let score = Math.round(successRate);

    // Context-based adjustments
    if (taskContext?.type === "ui" || taskContext?.type === "visual") {
      if (agent === "antigravity") score += 15;
      else if (agent === "codex") score -= 5;
    } else if (taskContext?.type === "test" || taskContext?.type === "fix") {
      if (agent === "codex") score += 10;
      else if (agent === "antigravity") score -= 5;
    } else if (
      taskContext?.type === "architecture" ||
      taskContext?.type === "research"
    ) {
      if (agent === "claude-code") score += 10;
    }

    // Penalize safety violations heavily
    if (safetyCount > 0) {
      score -= safetyCount * 20;
    }

    // Clamp score
    score = Math.max(0, Math.min(100, score));

    const reasoning = `Success rate: ${Math.round(successRate)}%. Needs fix: ${Math.round(needsFixRate)}%.`;

    scores.push({
      agent,
      recommendationScore: score,
      reasoning,
    });
  });

  return scores.sort((a, b) => b.recommendationScore - a.recommendationScore);
}

function generateRoutingStrategy(recommendations: RoutingScore[]): string {
  const lines: string[] = [];

  const topAgent = recommendations[0];
  lines.push(
    `1. **Try ${topAgent.agent} first** (${topAgent.recommendationScore}% confidence)`
  );

  if (recommendations[1]) {
    lines.push(
      `2. **If blocked**, fallback to ${recommendations[1].agent} (${recommendations[1].recommendationScore}%)`
    );
  }

  if (recommendations[2]) {
    lines.push(
      `3. **If still blocked**, try ${recommendations[2].agent} (${recommendations[2].recommendationScore}%)`
    );
  }

  lines.push(
    "4. If all fail, escalate to manual review or change approach."
  );

  return lines.map((l) => `- ${l}`).join("\n");
}
