import { DispatchJob, ApprovalRequest } from "../types";

/**
 * T051 (Part 5): Timeout & Fallback Summary
 *
 * Summarizes timeout events and which tasks were skipped_due_to_risk.
 * Pure function, returns Markdown string.
 */

export interface TimeoutSummary {
  totalTimedOut: number;
  totalApproved: number;
  totalRejected: number;
  timeoutRate: number; // percentage
  jobsByRiskLevel: Record<string, number>;
}

export function generateTimeoutFallbackSummary(
  jobs: DispatchJob[],
  approvals: ApprovalRequest[]
): string {
  const summary = summarizeTimeouts(jobs, approvals);

  return `# Approval Timeout & Fallback Summary

## Timeout Events

- **Total Timed Out**: ${summary.totalTimedOut}
- **Total Approved**: ${summary.totalApproved}
- **Total Rejected**: ${summary.totalRejected}
- **Timeout Rate**: ${summary.timeoutRate}%

## Tasks Skipped Due to Risk

${generateSkippedTasksList(jobs)}

## Analysis

${generateTimeoutAnalysis(summary)}

## Recommendations

${generateTimeoutRecommendations(summary)}

---
*Generated by Hermes (Observation Only — No Code Execution)*
`;
}

function summarizeTimeouts(
  jobs: DispatchJob[],
  approvals: ApprovalRequest[]
): TimeoutSummary {
  const skippedDueToRisk = jobs.filter(
    (j) => j.status === "skipped_due_to_risk"
  );

  const totalApproved = approvals.filter(
    (a) => a.status === "approved"
  ).length;
  const totalRejected = approvals.filter(
    (a) => a.status === "rejected"
  ).length;
  const totalTimedOut = approvals.filter(
    (a) => a.status === "timed_out"
  ).length;

  const totalApprovals = approvals.length;
  const timeoutRate =
    totalApprovals > 0
      ? Math.round((totalTimedOut / totalApprovals) * 100)
      : 0;

  const jobsByRiskLevel: Record<string, number> = {
    safe: 0,
    low: 0,
    medium: 0,
    high: 0,
    critical: 0,
  };

  skippedDueToRisk.forEach((job) => {
    jobsByRiskLevel[job.riskLevel]++;
  });

  return {
    totalTimedOut,
    totalApproved,
    totalRejected,
    timeoutRate,
    jobsByRiskLevel,
  };
}

function generateSkippedTasksList(jobs: DispatchJob[]): string {
  const skipped = jobs.filter((j) => j.status === "skipped_due_to_risk");

  if (skipped.length === 0) {
    return "**No tasks skipped due to timeout.** All risky tasks were either approved or rejected.";
  }

  const byRiskLevel: Record<string, DispatchJob[]> = {
    safe: [],
    low: [],
    medium: [],
    high: [],
    critical: [],
  };

  skipped.forEach((job) => {
    byRiskLevel[job.riskLevel].push(job);
  });

  return Object.entries(byRiskLevel)
    .filter(([, jobs]) => jobs.length > 0)
    .map(
      ([level, jobs]) => `
### ${capitalize(level)} Risk (${jobs.length} skipped)

${jobs
  .map(
    (j) => `- **Task ${j.taskId}** (Job ${j.id}): ${j.prompt?.substring(0, 60) || "No prompt"}`
  )
  .join("\n")}
`
    )
    .join("\n");
}

function generateTimeoutAnalysis(summary: TimeoutSummary): string {
  const insights: string[] = [];

  if (summary.timeoutRate > 50) {
    insights.push(
      "⚠️ **High timeout rate (>50%)** — Approval process may be bottlenecked."
    );
  } else if (summary.timeoutRate > 20) {
    insights.push(
      "📊 **Moderate timeout rate (20-50%)** — Some approval delays occurring."
    );
  } else if (summary.timeoutRate > 0) {
    insights.push(
      "✅ **Low timeout rate (<20%)** — Approval process is responsive."
    );
  } else {
    insights.push("✨ **No timeouts** — All approvals completed within window.");
  }

  if ((summary.jobsByRiskLevel.critical || 0) > 0) {
    insights.push(
      `⚠️ **${summary.jobsByRiskLevel.critical} critical-risk tasks** timed out — immediate attention needed.`
    );
  }

  if ((summary.jobsByRiskLevel.high || 0) > summary.jobsByRiskLevel.critical) {
    insights.push(
      `🔴 **${summary.jobsByRiskLevel.high} high-risk tasks** timed out.`
    );
  }

  if (summary.totalApproved > summary.totalTimedOut) {
    insights.push(
      `✅ **${summary.totalApproved} tasks approved** vs **${summary.totalTimedOut} timed out** — approvers are engaged.`
    );
  }

  return insights.map((i) => `- ${i}`).join("\n");
}

function generateTimeoutRecommendations(summary: TimeoutSummary): string {
  const rec: string[] = [];

  if (summary.timeoutRate > 30) {
    rec.push(
      "🔔 **Extend approval window** from 5 minutes to 10 minutes for complex tasks."
    );
    rec.push(
      "📢 **Notify approvers more frequently** — shorter batch windows?"
    );
  }

  if ((summary.jobsByRiskLevel.critical || 0) > 0) {
    rec.push("⛔ **Never let critical tasks timeout** — escalate immediately.");
  }

  if (summary.totalRejected > summary.totalApproved / 2) {
    rec.push(
      "🤔 **High rejection rate** — review task decomposition or risk classification."
    );
  }

  if (summary.totalApproved === 0 && summary.totalTimedOut === 0) {
    rec.push(
      "✅ **Excellent** — no risky tasks yet. Continue monitoring as workload increases."
    );
  }

  if (rec.length === 0) {
    rec.push("Continue monitoring approval patterns in next cycle.");
  }

  return rec.map((r) => `- ${r}`).join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
