// Obsidian-compatible Subagent Performance Memory Store
// Records subagent performance for long-term reuse decisions

import { promises as fs } from "fs";
import path from "path";

export type SubagentPerformanceRecord = {
  id: string;
  subagentId: string;
  parentAgent: "claude-code" | "codex" | "antigravity";
  taskId: string;
  workspaceId?: string;

  executedAt: string;
  durationMs: number;

  status: "success" | "failure" | "partial";
  qualityScore?: number; // 0-100

  changedFiles: string[];
  testsPassed?: number;
  testsFailed?: number;

  drift?: boolean; // Did execution drift from approved scope?
  scopeCreep?: boolean; // Did execution exceed approved scope?

  buildStatus?: "passed" | "failed" | "skipped";
  lintStatus?: "passed" | "failed" | "skipped";
  typeCheckStatus?: "passed" | "failed" | "skipped";

  summary?: string;
  errorMessage?: string;

  recommendReuse: boolean;
  recommendRetire: boolean;
  retireReason?: string;
};

export type PerformanceMemoryResult = {
  success: boolean;
  data?: any;
  error?: string;
};

/**
 * Get Obsidian workspace path for subagent memory
 */
export function getSubagentMemoryPath(): string {
  const cwd = process.cwd();
  return path.join(cwd, ".claude", "subagent-memory");
}

/**
 * Get path to individual subagent performance record (Markdown format)
 */
export function getSubagentPerformancePath(subagentId: string, recordId: string): string {
  const basePath = getSubagentMemoryPath();
  return path.join(basePath, `${subagentId}_${recordId}.md`);
}

/**
 * Write subagent performance record to Obsidian-compatible Markdown
 */
export async function writeSubagentPerformanceRecord(
  record: SubagentPerformanceRecord
): Promise<PerformanceMemoryResult> {
  try {
    const memoryPath = getSubagentMemoryPath();
    await fs.mkdir(memoryPath, { recursive: true });

    const recordPath = getSubagentPerformancePath(record.subagentId, record.id);

    const markdown = generatePerformanceMarkdown(record);

    const tmpPath = `${recordPath}.tmp`;
    await fs.writeFile(tmpPath, markdown, "utf-8");
    await fs.rename(tmpPath, recordPath);

    return { success: true, data: { path: recordPath } };
  } catch (error) {
    return {
      success: false,
      error: `Failed to write performance record: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * Generate Obsidian-compatible Markdown from performance record
 */
export function generatePerformanceMarkdown(record: SubagentPerformanceRecord): string {
  const timestamp = new Date(record.executedAt).toISOString();

  return `# ${record.subagentId} — Performance Record

**Date:** ${timestamp}
**Duration:** ${record.durationMs}ms
**Status:** ${record.status}
**Quality Score:** ${record.qualityScore ?? "—"}/100

## Task Context

- **Task ID:** \`${record.taskId}\`
- **Workspace ID:** \`${record.workspaceId ?? "—"}\`
- **Parent Agent:** ${record.parentAgent}

## Execution Results

### Outcome
- **Status:** ${record.status}
- **Summary:** ${record.summary ?? "—"}

### Quality Metrics
- **Quality Score:** ${record.qualityScore ?? "—"}
- **Tests Passed:** ${record.testsPassed ?? "—"}
- **Tests Failed:** ${record.testsFailed ?? "—"}

### Build & Checks
- **Build Status:** ${record.buildStatus ?? "skipped"}
- **Lint Status:** ${record.lintStatus ?? "skipped"}
- **TypeCheck Status:** ${record.typeCheckStatus ?? "skipped"}

## Files Changed

\`\`\`
${record.changedFiles.join("\n")}
\`\`\`

## Issues & Flags

- **Drift Detected:** ${record.drift ? "⚠️ Yes" : "✓ No"}
- **Scope Creep:** ${record.scopeCreep ? "⚠️ Yes" : "✓ No"}

## Recommendations

- **Recommend Reuse:** ${record.recommendReuse ? "✅ Yes" : "❌ No"}
- **Recommend Retire:** ${record.recommendRetire ? "⚠️ Yes" : "❌ No"}
${record.retireReason ? `  - **Reason:** ${record.retireReason}` : ""}

## Error Details

${record.errorMessage ? `\`\`\`\n${record.errorMessage}\n\`\`\`` : "—"}

---

*Generated by Agent Control Room — Subagent Performance Memory*
`;
}

/**
 * List all performance records for a subagent
 */
export async function listSubagentPerformanceRecords(
  subagentId: string
): Promise<PerformanceMemoryResult> {
  try {
    const memoryPath = getSubagentMemoryPath();
    const files = await fs.readdir(memoryPath);

    const recordFiles = files.filter((f) => f.startsWith(`${subagentId}_`) && f.endsWith(".md"));

    return { success: true, data: { records: recordFiles, count: recordFiles.length } };
  } catch (error) {
    return {
      success: false,
      error: `Failed to list performance records: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * Calculate aggregate performance metrics for a subagent
 */
export async function getSubagentAggregateMetrics(
  subagentId: string
): Promise<PerformanceMemoryResult> {
  try {
    const memoryPath = getSubagentMemoryPath();
    const files = await fs.readdir(memoryPath);

    const recordFiles = files.filter((f) => f.startsWith(`${subagentId}_`) && f.endsWith(".md"));

    if (recordFiles.length === 0) {
      return { success: true, data: { totalRuns: 0, successRate: 0, averageScore: 0 } };
    }

    // Count successes and calculate average score
    let successCount = 0;
    let totalScore = 0;
    let scoreCount = 0;

    // Simple parsing: read each file and count "Status: success" lines
    for (const file of recordFiles) {
      const filePath = path.join(memoryPath, file);
      const content = await fs.readFile(filePath, "utf-8");

      if (content.includes("**Status:** success")) {
        successCount++;
      }

      const scoreMatch = content.match(/\*\*Quality Score:\*\* (\d+)/);
      if (scoreMatch) {
        totalScore += parseInt(scoreMatch[1], 10);
        scoreCount++;
      }
    }

    const successRate = (successCount / recordFiles.length) * 100;
    const averageScore = scoreCount > 0 ? totalScore / scoreCount : 0;

    return {
      success: true,
      data: {
        totalRuns: recordFiles.length,
        successCount,
        failureCount: recordFiles.length - successCount,
        successRate: Math.round(successRate),
        averageScore: Math.round(averageScore * 100) / 100,
      },
    };
  } catch (error) {
    return {
      success: false,
      error: `Failed to calculate metrics: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}
