import type { GitHubConfig, PRCreationRequest, PRCreationResult } from "./github-types";

export function getGitHubConfig(): GitHubConfig | null {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;

  if (!token || !owner || !repo) return null;
  return { token, owner, repo };
}

export function buildPRBody(
  taskTitle: string,
  taskId: string,
  agent: string,
  changedFiles: string[],
  summary?: string
): string {
  const fileList = changedFiles.length > 0
    ? changedFiles.map((f) => `- \`${f}\``).join("\n")
    : "_No files tracked_";

  return `## Summary

${summary ?? `Task **${taskTitle}** completed by \`${agent}\`.`}

## Task

- **Task ID:** \`${taskId}\`
- **Agent:** ${agent}

## Changed Files

${fileList}

---

_Generated by [Agent Control Room](https://github.com/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO})_`;
}

export async function createPullRequest(
  config: GitHubConfig,
  request: PRCreationRequest
): Promise<PRCreationResult> {
  try {
    const response = await fetch(
      `https://api.github.com/repos/${config.owner}/${config.repo}/pulls`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${config.token}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
        body: JSON.stringify({
          title: request.title,
          body: request.body,
          head: request.head,
          base: request.base,
          draft: request.draft ?? false,
        }),
        signal: AbortSignal.timeout(15000),
      }
    );

    if (!response.ok) {
      const errorText = await response.text().catch(() => response.statusText);
      return { success: false, error: `GitHub API error ${response.status}: ${errorText}` };
    }

    const data = (await response.json()) as { number: number; html_url: string };
    return { success: true, prNumber: data.number, url: data.html_url };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
