import { AgentResult, AgentType, ResultStatus } from "../types";

/**
 * T051 (Part 2): Agent Performance Summary
 *
 * Aggregates ResultStatus counts per agent.
 * Pure function, returns Markdown string.
 */

export interface AgentPerformanceMetrics {
  agentId: AgentType;
  totalTasks: number;
  byStatus: Record<ResultStatus, number>;
  successRate: number; // 0-100
  averageScore: number;
}

export function generateAgentPerformanceSummary(
  results: AgentResult[]
): string {
  const metrics = aggregateByAgent(results);

  if (metrics.length === 0) {
    return `# Agent Performance Summary

No results yet. Waiting for first execution cycle.

---
*Generated by Hermes (Observation Only)*
`;
  }

  return `# Agent Performance Summary

${metrics
  .map(
    (m) => `## ${m.agentId}

- **Total Tasks**: ${m.totalTasks}
- **Success Rate**: ${m.successRate}%
- **Performance Score**: ${m.averageScore.toFixed(1)}/100

### Result Status Distribution

${Object.entries(m.byStatus)
  .filter(([_, count]) => count > 0)
  .map(([status, count]) => `- **${capitalize(status)}**: ${count}`)
  .join("\n")}
`
  )
  .join("\n")}

---
*Generated by Hermes (Observation Only — No Code Execution)*
`;
}

function aggregateByAgent(results: AgentResult[]): AgentPerformanceMetrics[] {
  const agents = new Map<AgentType, AgentPerformanceMetrics>();

  results.forEach((result) => {
    const agentId = result.agentId;

    if (!agents.has(agentId)) {
      agents.set(agentId, {
        agentId,
        totalTasks: 0,
        byStatus: {
          pass: 0,
          minor_fix: 0,
          qa_needed: 0,
          blocked: 0,
          safety_violation: 0,
        },
        successRate: 0,
        averageScore: 0,
      });
    }

    const metrics = agents.get(agentId)!;
    metrics.totalTasks++;
    metrics.byStatus[result.resultStatus]++;
  });

  // Calculate success rate for each agent
  agents.forEach((metrics) => {
    const passCount = metrics.byStatus.pass;
    const successRate =
      metrics.totalTasks > 0 ? (passCount / metrics.totalTasks) * 100 : 0;
    metrics.successRate = Math.round(successRate);

    // Simple score: pass = 100, minor_fix = 80, qa_needed = 60, blocked = 20, safety_violation = 0
    const scoreMap = {
      pass: 100,
      minor_fix: 80,
      qa_needed: 60,
      blocked: 20,
      safety_violation: 0,
    };

    const totalScore = Object.entries(metrics.byStatus).reduce(
      (sum, [status, count]) => sum + (scoreMap[status as ResultStatus] * count || 0),
      0
    );

    metrics.averageScore =
      metrics.totalTasks > 0 ? totalScore / metrics.totalTasks : 0;
  });

  return Array.from(agents.values()).sort(
    (a, b) => b.successRate - a.successRate
  );
}

function capitalize(s: string): string {
  return s
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
