import { AgentResult, ResultStatus } from "../types";

/**
 * T051 (Part 4): Prompt Improvement Suggestion
 *
 * Flags prompt patterns that consistently produce MinorFix/Blocked.
 * Pure function, returns Markdown string.
 */

export interface PromptPattern {
  pattern: string;
  frequency: number;
  associatedResultStatus: ResultStatus;
  suggestion: string;
}

export function generatePromptImprovementSuggestion(
  results: AgentResult[]
): string {
  const problemPatterns = identifyProblemPatterns(results);

  if (problemPatterns.length === 0) {
    return `# Prompt Improvement Suggestions

**Status**: No issues detected. Prompts are performing well.

---
*Generated by Hermes (Observation Only)*
`;
  }

  return `# Prompt Improvement Suggestions

## Detected Issues

${problemPatterns
  .map(
    (p, i) => `
### Issue ${i + 1}: ${p.pattern}

- **Frequency**: ${p.frequency} occurrence(s)
- **Associated Status**: ${p.associatedResultStatus}
- **Suggestion**: ${p.suggestion}
`
  )
  .join("\n")}

## Recommended Actions

${generateRecommendedActions(problemPatterns)}

---
*Generated by Hermes (Observation Only — No Code Execution)*
`;
}

function identifyProblemPatterns(results: AgentResult[]): PromptPattern[] {
  const patterns: PromptPattern[] = [];

  // Count minor_fix and blocked results
  const problemResults = results.filter(
    (r) => r.resultStatus === "minor_fix" || r.resultStatus === "blocked"
  );

  if (problemResults.length === 0) {
    return patterns;
  }

  // Simple heuristic: check for common keywords in summaries that correlate with problems
  const keywordFrequency: Record<string, number> = {};

  problemResults.forEach((result) => {
    const summary = result.extractedSummary || result.rawOutput || "";
    const words = summary.toLowerCase().split(/\s+/);

    words.forEach((word) => {
      if (word.length > 5) {
        // Only significant words
        keywordFrequency[word] = (keywordFrequency[word] || 0) + 1;
      }
    });
  });

  // Identify keywords that appear frequently in problem results
  const sortedKeywords = Object.entries(keywordFrequency)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 3); // Top 3 keywords

  sortedKeywords.forEach(([keyword, frequency]) => {
    if (frequency >= 2) {
      // Only significant patterns
      const problemCount = problemResults.length;
      const percentageOfProblems =
        (frequency / problemCount) * 100;

      let resultStatus: ResultStatus = "minor_fix";
      let suggestion = "";

      if (keyword.includes("type") || keyword.includes("error")) {
        resultStatus = "minor_fix";
        suggestion =
          "Prompt may be missing type definitions or error handling context. Add explicit TypeScript/type context to next prompt.";
      } else if (
        keyword.includes("test") ||
        keyword.includes("fail")
      ) {
        resultStatus = "blocked";
        suggestion =
          "Prompt may lack test requirements. Include specific test patterns and edge cases in acceptance criteria.";
      } else if (
        keyword.includes("boundary") ||
        keyword.includes("permission")
      ) {
        resultStatus = "blocked";
        suggestion =
          "Prompt may not specify file boundaries or restrictions. Be explicit about allowed/forbidden files.";
      } else {
        suggestion =
          "Review prompt context around this term. Consider adding clarifying constraints.";
      }

      patterns.push({
        pattern: `Keyword "${keyword}" (${frequency} times)`,
        frequency,
        associatedResultStatus: resultStatus,
        suggestion,
      });
    }
  });

  return patterns;
}

function generateRecommendedActions(patterns: PromptPattern[]): string {
  const actions: string[] = [];

  actions.push("1. **Review Senior Dev Prompt Compiler output** for missing context sections:");
  actions.push(
    "   - Explicit file boundaries (allowedFiles, doNotTouchFiles)"
  );
  actions.push("   - Type definitions and domain models");
  actions.push("   - Edge case acceptance criteria");

  if (
    patterns.some((p) => p.associatedResultStatus === "minor_fix")
  ) {
    actions.push(
      "\n2. **For minor_fix results**: Add more scaffolding code examples in prompts."
    );
  }

  if (
    patterns.some((p) => p.associatedResultStatus === "blocked")
  ) {
    actions.push(
      "\n3. **For blocked results**: Include explicit success criteria and error handling before dispatch."
    );
  }

  actions.push(
    "\n4. **Next iteration**: Re-run with improved prompts and compare ResultStatus distribution."
  );

  return actions.map((a) => `- ${a}`).join("\n");
}
