/**
 * Tests for lib/orchestration/subagent-registry.ts
 *
 * All fs/promises calls are mocked — no real disk I/O occurs.
 * The in-memory store is reset before each test via globalThis.
 */

import fs from "fs/promises";
import type { SubagentSpec } from "@/lib/orchestration/subagent-types";

// ─── Mock fs/promises ─────────────────────────────────────────────────────────

jest.mock("fs/promises", () => ({
  mkdir: jest.fn().mockResolvedValue(undefined),
  writeFile: jest.fn().mockResolvedValue(undefined),
  readFile: jest.fn().mockRejectedValue(Object.assign(new Error("ENOENT"), { code: "ENOENT" })),
  readdir: jest.fn().mockResolvedValue([]),
  unlink: jest.fn().mockResolvedValue(undefined),
}));

// ─── Import after mocks ───────────────────────────────────────────────────────

import {
  registerSubagent,
  getSubagent,
  listSubagents,
  updateSubagentPerformance,
  retireSubagent,
  validateSubagentSecurity,
  getBuiltinTemplates,
} from "@/lib/orchestration/subagent-registry";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function resetStore(): void {
  const g = globalThis as typeof globalThis & {
    __subagentRegistryStore?: Map<string, SubagentSpec>;
  };
  if (g.__subagentRegistryStore) {
    g.__subagentRegistryStore.clear();
  }
}

function makeSpec(overrides: Partial<SubagentSpec> = {}): SubagentSpec {
  return {
    id: "test/spec-a",
    name: "Test Spec A",
    parentAgent: "claude-code",
    runtimePreference: "claude-direct",
    role: "Test role",
    bestFor: ["testing"],
    notFor: ["production"],
    allowedFiles: ["lib/orchestration/**"],
    blockedFiles: [".env"],
    allowedCommands: ["pnpm typecheck"],
    blockedCommands: ["git push"],
    promptTemplatePath: "templates/test.md",
    obsidianPath: "subagents/test",
    source: "builtin",
    successCount: 0,
    failureCount: 0,
    status: "active",
    securityReport: { level: "clean", message: "pre-validated" },
    ...overrides,
  };
}

// ─── Tests ───────────────────────────────────────────────────────────────────

beforeEach(() => {
  resetStore();
  jest.clearAllMocks();
});

// ---------------------------------------------------------------------------
// validateSubagentSecurity
// ---------------------------------------------------------------------------

describe("validateSubagentSecurity", () => {
  it("returns clean for a safe builtin spec", () => {
    const report = validateSubagentSecurity(makeSpec());
    expect(report.level).toBe("clean");
  });

  it("returns rejected when allowedCommands contains a dangerous command", () => {
    const spec = makeSpec({ allowedCommands: ["git push origin main"] });
    const report = validateSubagentSecurity(spec);
    expect(report.level).toBe("rejected");
    expect(report.details?.some((d) => d.includes("git push origin main"))).toBe(true);
  });

  it("returns rejected when allowedFiles contains .env", () => {
    const spec = makeSpec({ allowedFiles: [".env.local"] });
    const report = validateSubagentSecurity(spec);
    expect(report.level).toBe("rejected");
  });

  it("returns rejected when allowedFiles contains package.json", () => {
    const spec = makeSpec({ allowedFiles: ["package.json"] });
    const report = validateSubagentSecurity(spec);
    expect(report.level).toBe("rejected");
  });

  it("returns warning when external source has no sourceHash", () => {
    const spec = makeSpec({ source: "clawhub", sourceHash: undefined });
    const report = validateSubagentSecurity(spec);
    expect(report.level).toBe("warning");
    expect(report.details?.some((d) => d.includes("sourceHash"))).toBe(true);
  });

  it("returns warning when a command appears in both allowedCommands and blockedCommands", () => {
    const spec = makeSpec({
      allowedCommands: ["pnpm lint"],
      blockedCommands: ["pnpm lint"],
    });
    const report = validateSubagentSecurity(spec);
    expect(report.level).toBe("warning");
  });
});

// ---------------------------------------------------------------------------
// registerSubagent
// ---------------------------------------------------------------------------

describe("registerSubagent", () => {
  it("registers a valid spec and returns it", async () => {
    const spec = makeSpec();
    const result = await registerSubagent(spec);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.id).toBe(spec.id);
    }
  });

  it("attaches the generated securityReport to the stored spec", async () => {
    const spec = makeSpec({ source: "clawhub" }); // triggers warning
    const result = await registerSubagent(spec);
    expect(result.success).toBe(true);
    if (result.success) {
      // The stored spec's report is regenerated by validateSubagentSecurity
      expect(result.data.securityReport.level).toBe("warning");
    }
  });

  it("blocks a spec with a rejected security report", async () => {
    const spec = makeSpec({ allowedCommands: ["git push origin main"] });
    const result = await registerSubagent(spec);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toMatch(/rejected/i);
    }
  });

  it("persists to disk after registration", async () => {
    const mockFs = fs as jest.Mocked<typeof fs>;
    await registerSubagent(makeSpec());
    expect(mockFs.writeFile).toHaveBeenCalled();
  });
});

// ---------------------------------------------------------------------------
// getSubagent
// ---------------------------------------------------------------------------

describe("getSubagent", () => {
  it("returns the spec after registration", async () => {
    await registerSubagent(makeSpec({ id: "test/spec-b" }));
    const result = await getSubagent("test/spec-b");
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.id).toBe("test/spec-b");
    }
  });

  it("returns error for unknown id", async () => {
    const result = await getSubagent("nonexistent");
    expect(result.success).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// listSubagents
// ---------------------------------------------------------------------------

describe("listSubagents", () => {
  it("returns all registered subagents", async () => {
    await registerSubagent(makeSpec({ id: "test/a", parentAgent: "claude-code" }));
    await registerSubagent(makeSpec({ id: "test/b", parentAgent: "codex" }));
    const result = await listSubagents();
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.length).toBe(2);
    }
  });

  it("filters by parentAgent", async () => {
    await registerSubagent(makeSpec({ id: "test/a", parentAgent: "claude-code" }));
    await registerSubagent(makeSpec({ id: "test/b", parentAgent: "codex" }));
    const result = await listSubagents("codex");
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.every((s) => s.parentAgent === "codex")).toBe(true);
      expect(result.data.length).toBe(1);
    }
  });

  it("returns empty array when registry is empty", async () => {
    const result = await listSubagents();
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data).toEqual([]);
    }
  });
});

// ---------------------------------------------------------------------------
// updateSubagentPerformance
// ---------------------------------------------------------------------------

describe("updateSubagentPerformance", () => {
  it("increments successCount on success=true", async () => {
    await registerSubagent(makeSpec({ id: "test/perf" }));
    const result = await updateSubagentPerformance("test/perf", true);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.successCount).toBe(1);
      expect(result.data.failureCount).toBe(0);
    }
  });

  it("increments failureCount on success=false", async () => {
    await registerSubagent(makeSpec({ id: "test/perf2" }));
    const result = await updateSubagentPerformance("test/perf2", false);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.failureCount).toBe(1);
      expect(result.data.successCount).toBe(0);
    }
  });

  it("sets lastUsedAt after update", async () => {
    await registerSubagent(makeSpec({ id: "test/perf3" }));
    const result = await updateSubagentPerformance("test/perf3", true);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.lastUsedAt).toBeDefined();
    }
  });

  it("computes averageQualityScore when score is provided", async () => {
    await registerSubagent(makeSpec({ id: "test/perf4", successCount: 0, failureCount: 0 }));
    await updateSubagentPerformance("test/perf4", true, 80);
    const result = await updateSubagentPerformance("test/perf4", true, 100);
    expect(result.success).toBe(true);
    if (result.success) {
      // Running average of two runs
      expect(result.data.averageQualityScore).toBeGreaterThan(0);
    }
  });

  it("returns error for unknown subagent id", async () => {
    const result = await updateSubagentPerformance("nonexistent", true);
    expect(result.success).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// retireSubagent
// ---------------------------------------------------------------------------

describe("retireSubagent", () => {
  it("sets status to retired", async () => {
    await registerSubagent(makeSpec({ id: "test/retire" }));
    const result = await retireSubagent("test/retire", "no longer needed");
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.status).toBe("retired");
    }
  });

  it("includes the reason in the securityReport message", async () => {
    await registerSubagent(makeSpec({ id: "test/retire2" }));
    const result = await retireSubagent("test/retire2", "deprecated api");
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.securityReport.message).toContain("deprecated api");
    }
  });

  it("returns error for unknown id", async () => {
    const result = await retireSubagent("nonexistent", "reason");
    expect(result.success).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// getBuiltinTemplates
// ---------------------------------------------------------------------------

describe("getBuiltinTemplates", () => {
  it("returns templates for all three parent agents", () => {
    const templates = getBuiltinTemplates();
    const parents = new Set(templates.map((t) => t.parentAgent));
    expect(parents.has("claude-code")).toBe(true);
    expect(parents.has("codex")).toBe(true);
    expect(parents.has("antigravity")).toBe(true);
  });

  it("includes expected builtin ids", () => {
    const templates = getBuiltinTemplates();
    const ids = templates.map((t) => t.id);
    expect(ids).toContain("claude/architecture-reviewer");
    expect(ids).toContain("codex/regression-qa");
    expect(ids).toContain("antigravity/visual-qa");
  });

  it("all builtin templates have clean security reports", () => {
    const templates = getBuiltinTemplates();
    for (const t of templates) {
      expect(t.securityReport.level).toBe("clean");
    }
  });

  it("all builtin templates have source=builtin", () => {
    const templates = getBuiltinTemplates();
    for (const t of templates) {
      expect(t.source).toBe("builtin");
    }
  });

  it("no builtin template has a dangerous allowedCommand", () => {
    const templates = getBuiltinTemplates();
    for (const t of templates) {
      const report = validateSubagentSecurity(t);
      expect(report.level).not.toBe("rejected");
    }
  });
});
